spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/gulimall_oms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 50000
  application:
    name: shopping-order
  cloud:
    nacos:
      discovery:
        server-addr: #nacos注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.102
  session:
    store-type: redis

  rabbitmq:
    host: #
    username: niceseason
    password: mo19960729
    listener:
      simple:
        acknowledge-mode: manual
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9001


# 自定义线程池参数
shopping:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
management:
  endpoints:
    web:
      exposure:
        include: '*'
