spring:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Query=url, qq

        #将路径为Path=/api/thirdparty/**转发至第三方服务模块
        - id: third_party_route
          uri: lb://shopping-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/product转发shopping-product微服务
        - id: product_route
          uri: lb://shopping-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/member/**转发至会员服务
        - id: shopping-member
          uri: lb://shopping-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/ware/**转发至仓库服务
        - id: shopping-ware
          uri: lb://shopping-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/coupon/**转发至优惠服务
        - id: shopping-coupon
          uri: lb://shopping-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        #将路径为Path=/api/**转发至后台管理
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        #将主机地址为search.shopping.com转发至shopping-search
        - id: shopping_serach_host
          uri: lb://shopping-search
          predicates:
            - Host=search.shopping.com

        #将主机地址为auth.shopping.com转发至shopping-auth
        - id: shopping_auth_host
          uri: lb://shopping-auth-server
          predicates:
            - Host=auth.shopping.com


      #将主机地址为search.shopping.com转发至shopping-search
        - id: shopping_cart_host
          uri: lb://shopping-cart
          predicates:
            - Host=cart.shopping.com

        #将主机地址为order.shopping.com转发至shopping-order
        - id: shopping_order_host
          uri: lb://shopping-order
          predicates:
            - Host=order.shopping.com

        #将主机地址为seckill.shopping.com转发至shopping-seckill
        - id: shopping_seckill_host
          uri: lb://shopping-seckill
          predicates:
            - Host=seckill.shopping.com

        #将主机地址为**.shopping.com转发至shopping-product
        - id: shopping_host
          uri: lb://shopping-product
          predicates:
            - Host=**.shopping.com
    sentinel:
      transport:
        dashboard: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'





